use poker

insert into mttr_nlhe_sessions(
  poker_session_date,
  delta,
  initial_stake,
  num_hands,
  big_blind_amount,
  buy_in,
  bounty,
  entry_fee,
  rebuys,
  add_on,
  num_entries,
  places_paid,
  prize_pool,
  num_players,
  place,
  winnings,
  num_bounties,
  bounties,
  num_flops_seen,
  num_showdowns,
  pots_won_at_showdown,
  pots_won_without_showdown,
  tournament_letter,
  sum_in_chips,
  num_rebuys,
  added_on,
  tournament_rebuys,
  tournament_add_ons
)
select
  poker_session_date,
  delta,
  initial_stake,
  num_hands,
  big_blind_amount,
  buy_in,
  bounty,
  entry_fee,
  rebuys,
  add_on,
  num_entries,
  places_paid,
  prize_pool,
  num_players,
  place,
  winnings,
  num_bounties,
  bounties,
  num_flops_seen,
  num_showdowns,
  pots_won_at_showdown,
  pots_won_without_showdown,
  tournament_letter,
  sum_in_chips,
  num_rebuys,
  added_on,
  tournament_rebuys,
  tournament_add_ons
from poker_sessions
where poker_style = 6 and poker_flavor = 3;

quit
